In [36]:
import tensorflow as tf
import numpy as np

In [2]:
x = tf.constant(5)
y = tf.constant(6)

In [3]:
z = x + y

In [4]:
z

<tf.Tensor 'add:0' shape=() dtype=int32>

In [5]:
sess = tf.Session()
sess.run(z)

11

In [6]:
sess.close()

In [7]:
x1 = tf.Variable(6)
y1 = tf.Variable(7)

Instructions for updating:
Colocations handled automatically by placer.


In [9]:
z1 = x1 + y1

In [15]:
init = tf.global_variables_initializer()

In [17]:
with tf.Session() as sess:
    init.run()
    print(sess.run(z1))

13


In [29]:
random_1 =  tf.random_normal((5,5))

In [30]:
sess = tf.Session()

In [31]:
sess.run(random_1)

array([[-0.74583167,  0.21827869, -0.1797421 ,  0.05215181, -0.35715085],
       [-0.06309544,  0.7597785 , -1.3453947 ,  0.06964639,  0.31331387],
       [-0.3008386 , -1.1692389 ,  1.0150166 ,  1.7755965 ,  0.23436688],
       [-0.49546573, -0.30327132,  0.57240355,  0.00906922,  1.9314281 ],
       [-0.32320377, -1.5634028 , -2.5098913 ,  1.5334814 ,  1.2049086 ]],
      dtype=float32)

In [32]:
random_2 = tf.random_uniform((5,1))

In [33]:
sess.run(random_2)

array([[0.5115764 ],
       [0.64495504],
       [0.687343  ],
       [0.797323  ],
       [0.55930865]], dtype=float32)

In [24]:
arr = tf.add(random_1,random_2)

In [25]:
sess.run(arr)

array([[ 0.5959636 ],
       [-0.04564804],
       [-2.0427618 ],
       [ 1.5932047 ],
       [ 0.46072248]], dtype=float32)

In [26]:
# Placeholders
x = tf.placeholder(dtype=tf.float32, shape=(5,5))
y = tf.placeholder(dtype=tf.float32, shape=(5,1))

In [27]:
result = tf.matmul(x,y)

In [28]:
result

<tf.Tensor 'MatMul:0' shape=(5, 1) dtype=float32>

In [37]:
with tf.Session() as sess:
    op = sess.run(result,feed_dict = {x:np.random.random((5,5)), y:np.random.random((5,1))})
    print(op)

[[2.4957967]
 [2.0600252]
 [1.6063817]
 [1.3325737]
 [1.8571856]]
